### ISSUE TITLE
math util purpose

### ISSUE THREAD

**Issue by mscottnelson** [taylorbf/Musicians-Toolkit#5]
Is there a particular reason you want to use a dedicated math util inside of some of these models instead of Math? I only ask because of the performance hit in JS of making function calls, and it seems like that *could* come up in a music tool. Maybe this doesn't matter if you are ultimately planning on having a 'compiled' mini for production environments?

**Comment by taylorbf** [comment]
The purpose of the math utils is to have shorthands for common tasks -- both within the development code and as part of the API.

So, someone using the toolkit can write `mt.ri( 5, 10 )` and get a random integer from 5 to 10. I want this to aid the composition process for the user.

You could argue that within the development code we should write out the longform versions using Math...

The way it is now makes the code more readable, for example being able to use `math.scale()` instead of doing a bunch of math.

A function hit isn't terrible. At one point I measured doing 1000 or more and I think it took 1 ms. Feel free to run some performance tests on using math util vs Math longform, and if it's sizable, we can not use the math util within the dev code, but still make it available the the user in the API.

**Comment by mscottnelson** [comment]
Makes sense. I'm am generally in favor of readability / ease of use over performance.

**Comment by taylorbf** [comment]
Me too, although I am actually trying to be _very_ conscious of performance in this rewrite. In fact the switch to SVG from canvas, which has been a _ton_ of work, was due to tests in mobile where SVG was a lot less laggy. It also looks better. : )

But I don't think a function call will get us in trouble. And if it does, we can edit.
